AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template for DevSecOps Demo Jenkins build server
Parameters:
  ImageId:
    Default: ami-0c4f7023847b90238
    Description: 'EC2 AMI ID '
    Type: String
  InstanceType:
    Default: t2.medium
    Description: 'EC2 instance type '
    Type: String
  KeyName:
    Default: devsecops_key
    Description: 'Key'
    Type: String
  SecurityGroupIds:
    Default: sg-033fa747aa5932492
    Description: SecurityGroup
    Type: String
  SubnetId:
    Default: subnet-0f9d6d02ec211aa92
    Description: Subnet
    Type: String
Resources:
  JenkinsServer:
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref SecurityGroupIds
      SubnetId: !Ref SubnetId
      UserData:
        Fn::Base64: !Sub |
           #!/bin/bash -xe
           wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
           sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
           sudo apt update
           sudo ufw allow 8080
           sudo ufw allow OpenSSH
           sudo ufw enable
           sudo apt-get install -y default-jdk
           sudo apt install -y docker.io maven gradle
           sudo apt install -y jenkins
           sudo systemctl start jenkins
           sudo systemctl status jenkins
      Tags:
        - Key: Name
          Value: Jenkins_server
        - Key: Stack_name
          Value: stack_DevSecOps
        - Key: Type
          Value: Jenkins
    Type: AWS::EC2::Instance
    
Outputs:
  JenkinsServerInstanceId:
    Value: !Ref 'JenkinsServer'
    Description: Instance Id of instance
  JenkinsServerPrimaryPrivateIPAddress:
    Value: !GetAtt [JenkinsServer, PrivateIp]
    Description: Primary private IP address